version: '3.8'

services:
  db:
    build: .
    container_name: movie_rental_db
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # Named volume for persistent data
      - mysql_data:/var/lib/mysql
      # Bind mount for initialization scripts
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - movie-rental-network

networks:
  movie-rental-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
